add cronjob for periodically getting all movie pages
menkuichan/data-worker pull request #5
Opened 2020-01-10 09:19 UTC by IlonaMenkui

2020-01-10 10:03 UTC, ok2ju requested changes

2020-01-10 10:03 UTC, ok2ju commented on index.js
> +new CronJob('0 0 12 * * * *', () => putAllMoviePagesInDatabase(), null, true, 'America/Los_Angeles');
You trying to start Cron and than save movies, but you not sure that db connection established

2020-01-10 14:29 UTC, ok2ju requested changes

2020-01-10 14:29 UTC, ok2ju commented on index.js
> +var CronJob = require('cron').CronJob;
Why you use `var` here? Please use modern approach, e.g. `const { CronJob } = require('cron');`

2020-01-10 14:29 UTC, ok2ju commented on index.js
> +  new CronJob('0 0 12 * * * *', () => putAllMoviePagesInDatabase(), null, true, 'America/Los_Angeles');
Why you use `America/Los_Angeles` locale? Maybe try to use our local locale?

2020-01-10 14:29 UTC, ok2ju commented on index.js
> +  putAllMoviePagesInDatabase();
You don't need to call `putAllMoviePagesInDatabase` here. Only inside cron callback.

2020-01-10 14:29 UTC, ok2ju commented on index.js
> +const putAllMoviePagesInDatabase = async () => {
Let's name this function something like `populateDB`. WDYT?

2020-01-10 14:29 UTC, ok2ju commented on index.js
> +  putAllMoviePagesInDatabase();
If you want to start cron immediately use `start` method of `cron` - [example](https://github.com/kelektiv/node-cron/blob/master/examples/every_10_minutes.js)

2020-01-10 14:37 UTC, ok2ju commented on index.js
>  const server = http.createServer((req, res) => {
I think we can remove this redundant callback now. Just start server without callback.

2020-01-10 14:38 UTC, ok2ju requested changes

2020-01-10 14:38 UTC, ok2ju commented on index.js
>  const server = http.createServer((req, res) => {
I think we can remove this redundant callback now. Just start server without callback.

2020-01-13 09:16 UTC, IlonaMenkui commented on index.js
>      const { results, total_pages } = await getMovies(1);
@ok2ju is it correct use 'results' inside for? because 'results' is already declared in the upper scope.

2020-01-13 09:18 UTC, IlonaMenkui commented on index.js
>      const { results, total_pages } = await getMovies(1);
should i just rename it?

2020-01-13 17:14 UTC, ok2ju approved these changes

2020-01-13 17:14 UTC, merged